[package]
name = "MyBlockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
rsa    = "0.9"       # or latest
sha2   = "0.10"
hex    = "0.4"
anyhow = "1.0"
chrono = "0.4.41"
secp256k1 = { version = "0.31.1", features = ["rand", "hashes"] }
